config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'contact/index'

  get 'developer/index'

  get 'base/index'

  resources :paths
  resources :points
  resources :users

  root 'base#index'
  
  namespace :api, defaults: { format: 'json' } do
    resources :paths
  end

end

app/models/path.rb
class Path < ActiveRecord::Base
    belongs_to :user
    has_many :points_in_paths
    has_many :points, :through => :points_in_paths
    enum status: [:published, :unpublished]
end

app/controllers/api/paths_controller.rb
class Api::PathsController < ApplicationController
  before_action :set_statuses
  before_action :set_path, only: [:show, :edit, :update, :destroy]

  # GET /paths
  # GET /paths.json
  def index
    @paths = Path.all
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = Path.new
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths
  # POST /paths.json
  def create
    @path = Path.new(path_params)

    respond_to do |format|
      if @path.save
        # format.html { redirect_to @path, notice: 'Path was successfully created.' }
        format.json { render :show, status: :created, location: @path }
      else
        # format.html { render :new }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paths/1
  # PATCH/PUT /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        # format.html { redirect_to @path, notice: 'Path was successfully updated.' }
        format.json { render :show, status: :ok, location: @path }
      else
        # format.html { render :edit }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1
  # DELETE /paths/1.json
  def destroy
    @path.destroy
    respond_to do |format|
    #   format.html { redirect_to paths_url, notice: 'Path was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def path_params
      params.require(:path).permit(:name, :country, :city, :description, :duration, :likes, :status)
    end
    
    def set_statuses
      @statuses = Path.statuses
    end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_statuses
  before_action :set_path, only: [:show, :edit, :update, :destroy]

  # GET /paths
  # GET /paths.json
  def index
    @paths = Path.all
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = Path.new
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths
  # POST /paths.json
  def create
    @path = Path.new(path_params)

    respond_to do |format|
      if @path.save
        format.html { redirect_to @path, notice: 'Path was successfully created.' }
        format.json { render :show, status: :created, location: @path }
      else
        format.html { render :new }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paths/1
  # PATCH/PUT /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        format.html { redirect_to @path, notice: 'Path was successfully updated.' }
        format.json { render :show, status: :ok, location: @path }
      else
        format.html { render :edit }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1
  # DELETE /paths/1.json
  def destroy
    @path.destroy
    respond_to do |format|
      format.html { redirect_to paths_url, notice: 'Path was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def path_params
      params.require(:path).permit(:name, :country, :city, :description, :duration, :likes, :status)
    end
    
    def set_statuses
      @statuses = Path.statuses
    end
end

app/helpers/api/paths_helper.rb
module Api::PathsHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/paths/_form.html.erb
<%= form_for(@path) do |f| %>
  <% if @path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
      <% @path.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :likes %><br>
    <%= f.number_field :likes %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect {|s| [s[0].humanize, s[0]]}, selected: @path.status), {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paths/edit.html.erb
<h1>Editing Path</h1>

<%= render 'form' %>

<%= link_to 'Show', @path %> |
<%= link_to 'Back', paths_path %>

app/views/paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Paths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>City</th>
      <th>Description</th>
      <th>Duration</th>
      <th>Likes</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.name %></td>
        <td><%= path.country %></td>
        <td><%= path.city %></td>
        <td><%= path.description %></td>
        <td><%= path.duration %></td>
        <td><%= path.likes %></td>
        <td><%= path.status %></td>
        <td><%= link_to 'Show', path %></td>
        <td><%= link_to 'Edit', edit_path_path(path) %></td>
        <td><%= link_to 'Destroy', path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Path', new_path_path %>

app/views/paths/new.html.erb
<h1>New Path</h1>

<%= render 'form' %>

<%= link_to 'Back', paths_path %>

app/views/paths/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @path.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @path.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @path.city %>
</p>

<p>
  <strong>Description:</strong>
  <%= @path.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @path.duration %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @path.likes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @path.status %>
</p>

<%= link_to 'Edit', edit_path_path(@path) %> |
<%= link_to 'Back', paths_path %>